# Change these first
owner: PhoenixR49 # Your GitHub organization or username, where this repository lives
repo: stormix-status-page # The name of this repository

sites:
  - name: Stormix Website
    url: https://stormixmusic.com
  - name: Stormix Smart Links
    url: https://play.stormixmusic.com
  - name: Stormix Bio
    url: https://bio.stormixmusic.com

status-website:
  # cname: status.stormixmusic.com
  baseUrl: /stormix-status-page
  logoUrl: https://stormixmusic.com/assets/branding/logo/logo.png
  name: Stormix Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Main Website
      href: https://stormixmusic.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
