# Change these first
owner: PhoenixR49 # Your GitHub organization or username, where this repository lives
repo: stormix-status-page # The name of this repository

sites:
  - name: Stormix Website
    url: https://stormixmusic.com
  - name: Stormix Smart Links
    url: https://play.stormixmusic.com
  - name: Stormix Bio
    url: https://bio.stormixmusic.com

status-website:
  # cname: status.stormixmusic.com
  baseUrl: /stormix-status-page
  logoUrl: https://stormixmusic.com/assets/branding/logo/logo.png
  name: Stormix Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
